AppBundle\Entity\Place:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    properties:
        name:
            - NotBlank: ~
            - Type: string
        address:
            - NotBlank: ~
            - Type: string
        prices:
            - Valid: ~
            - AppBundle\Form\Validator\Constraint\PriceTypeUnique: ~
AppBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
    properties:
        firstname:
            - NotBlank: ~
            - Type: string
        lastname:
            - NotBlank: ~
            - Type: string
        email:
            - NotBlank: ~
            - Email: ~
        plainPassword:
            - NotBlank: { groups: [New, FullUpdate] }
            - Type: string
            - Length:
                min: 4
                max: 50
AppBundle\Entity\Price:
    properties:
        type:
            - NotNull: ~
            - Choice:
                choices: [ public , perso ]
        value:
            - NotNull: ~
            - Type: integer
            - GreaterThanOrEqual:
                value: 0
AppBundle\Entity\Theme:
    properties:
        name:
            - NotNull: ~
            - Choice:
                choices: [art, architecture, history, sf, sport]
        value:
            - NotNull: ~
            - Type: integer
            - GreaterThan:
                value: 0
            - LessThanOrEqual:
                value: 10
AppBundle\Entity\Preference:
    properties:
        name:
            - NotNull: ~
            - Choice:
                choices: [art, architecture, history, sf, sport]
        value:
            - NotNull: ~
            - Type: numeric
            - GreaterThan:
                value: 0
            - LessThanOrEqual:
                value: 10
AppBundle\Entity\Credentials:
    properties:
        login:
            - NotBlank: ~
            - Type: string
        password:
            - NotBlank: ~
            - Type: string